language: node_js
dist: bionic
os: linux

node_js:
  - '10'
  - '12'
  - '14'

services:
  - docker

install:
  - yarn install

script:
  - yarn lint
  - yarn lint:test
  - docker-compose pull
  - yarn test
