name: Test
on:
  push:
    branches:
      - main
      - master
    tags:
      - '!*' # Do not execute on tags
  pull_request:
    branches:
      - main
      - master
jobs:
  test:
    strategy:
      matrix:
        node: [ '22', '20', '18']
    name: test/node ${{ matrix.node }}/ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
    - run: npm install -g yarn
    - run: yarn install
    - run: yarn run lint
    - run: docker compose pull
    - run: yarn run test
